### ISSUE TITLE
Unsure how the offset works for plaintext attack

### ISSUE THREAD

**Issue by Belval** [mferland/libzc#3]
I have a `.txt` file which contains a string of length >1000 bytes.
I have a `.zip` file which contains the compressed string, of length <90 bytes.

The example given in the help section seems to map offsets 1:1 which does not make sense here since my plaintext was heavily compressed.

Second question: What it the "BEGIN" offset? How is that value chosen?

Thank you

**Comment by mferland** [comment]
Hi,

The man page is a bit clearer.

If the ciphertext (your zip file) is compressed, your plaintext (the content of the txt file) should also be compressed using the same compression algorithm. This is what makes the attack a little bit tricky sometimes.

Simply put, the ciphertext is encrypted, the plaintext is not encrypted and that is the _only_ difference.

The BEGIN offset is the offset of the first byte of the ciphertext in the file. You can find this offset by using the 'info' sub-command. Look at the OFFSETS columns, the first number is the BEGIN, the second and third numbers are the start and end offsets of the actual file content (encrypted files are always prepended by 12 pseudo-random bytes).

Hope that helps!
